import "normalize.css/normalize.css";
import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import Providers from "../providers/Providers";
import styles from "./layout.module.css";
import Cart from "../components/Cart/Cart";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className={styles.app}>
            <Header />
            <main className={styles.main}>{children}</main>
            <Cart />
            <Footer />
          </div>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
